[package]
name = "vmware_horizon-exporter"
version = "1.0.0-20230422"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
